import type { Metadata } from "next";
import { PrivateRoute } from "@/feature/auth/ui/private-router";
import { SideBar } from "@/entity/sidebar/ui";
import { SidebarProvider } from "@/shared/components/ui/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <PrivateRoute>
      <div className="relative flex flex-col w-[100vw] overflow-x-hidden">
        <SidebarProvider >
          <SideBar />
          {children}
        </SidebarProvider>
      </div>
    </PrivateRoute>

  );
}
